spring.application.name=weekly-report-generator

spring.datasource.url=jdbc:postgresql://localhost:5432/weekly_reports
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

spring.jwt.secret=change-this-to-a-long-random-base64-string
spring.jwt.expiration-ms=86400000

gemini.api-key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash
gemini.api-url=########